name: pomodoro_timer
description: A Pomodoro timer with flexible controls and timer customizations

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^7.6.4
  signals_flutter: ^5.0.0
  google_fonts: ^6.2.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# dependency_overrides:

flutter:

  uses-material-design: true

  assets:
    - icons/icons8-pause-100-white-blured.png
    - icons/icons8-play-100-white-blured.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  fonts:
    - family: AvenirNext
      fonts:
        - asset: fonts/avenirnext-regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
